version: "2"
services:
  cron:
    image: manaphp/php74:4.1
    volumes: 
      - ./:/var/www/html
      - ./docker/cron.d:/tmp/cron.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cron/log:/var/log/cron
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cron/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cron/tmp:/var/www/html/tmp
    restart: always